Repository PEER-Re/PEERRE-SERVER, pull requests merged in 2024-02, with the labels that each got.

#2 [chore] #1 프로젝트 초기 세팅
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/umc/peerre/PeerreApplication.java
  src/main/java/org/umc/peerre/domain/user/controller/UserController.java
  src/main/java/org/umc/peerre/domain/user/dto/response/UserTokenResponseDto.java
  src/main/java/org/umc/peerre/domain/user/service/UserService.java
  src/main/java/org/umc/peerre/global/common/BaseTimeEntity.java
  src/main/java/org/umc/peerre/global/common/SuccessCode.java
  src/main/java/org/umc/peerre/global/common/SuccessResponse.java
  src/main/java/org/umc/peerre/global/config/CorsConfig.java
  src/main/java/org/umc/peerre/global/config/JpaConfig.java
  src/main/java/org/umc/peerre/global/config/WebConfig.java
  src/main/java/org/umc/peerre/global/config/auth/ExceptionHandlerFilter.java
  src/main/java/org/umc/peerre/global/config/auth/SecurityConfig.java
  src/main/java/org/umc/peerre/global/config/auth/UserAuthentication.java
  src/main/java/org/umc/peerre/global/config/auth/UserId.java
  src/main/java/org/umc/peerre/global/config/auth/UserIdArgumentResolver.java
  src/main/java/org/umc/peerre/global/config/auth/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/org/umc/peerre/global/config/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/org/umc/peerre/global/config/auth/jwt/JwtProvider.java
  src/main/java/org/umc/peerre/global/error/ErrorCode.java
  src/main/java/org/umc/peerre/global/error/dto/ErrorResponse.java
  src/main/java/org/umc/peerre/global/error/exception/BusinessException.java
  src/main/java/org/umc/peerre/global/error/exception/ConflictException.java
  src/main/java/org/umc/peerre/global/error/exception/EntityNotFoundException.java
  src/main/java/org/umc/peerre/global/error/exception/ForbiddenException.java
  src/main/java/org/umc/peerre/global/error/exception/InternalServerException.java
  src/main/java/org/umc/peerre/global/error/exception/InvalidValueException.java
  src/main/java/org/umc/peerre/global/error/exception/UnauthorizedException.java
  src/main/java/org/umc/peerre/global/error/handler/GlobalExceptionHandler.java
  src/test/java/org/umc/peerre/PeerreApplicationTests.java
Labels: CHORE

#7 [fix] #6 피드백 평가 취소 후에 변경하는 경우 고려하여 수정
  src/main/java/org/umc/peerre/domain/feedback/dto/request/FeedbackRequest.java
  src/main/java/org/umc/peerre/domain/feedback/service/FeedbackService.java
Labels: FIX

#10 [feat] 새 프로젝트 생성 api 구현
  src/main/java/org/umc/peerre/domain/project/constant/Status.java
  src/main/java/org/umc/peerre/domain/project/controller/ProjectController.java
  src/main/java/org/umc/peerre/domain/project/dto/request/CreateProjectRequestDto.java
  src/main/java/org/umc/peerre/domain/project/entity/Project.java
  src/main/java/org/umc/peerre/domain/project/service/ProjectService.java
Labels: FEAT

#12 [feat] 프로젝트 종료 api 구현
  src/main/java/org/umc/peerre/domain/project/controller/ProjectController.java
  src/main/java/org/umc/peerre/domain/project/service/ProjectService.java
  src/main/java/org/umc/peerre/global/error/ErrorCode.java
Labels: FEAT

#14 Featrue/#8
  src/main/java/org/umc/peerre/domain/feedback/controller/FeedbackController.java
  src/main/java/org/umc/peerre/domain/feedback/dto/response/FeedbackResponse.java
  src/main/java/org/umc/peerre/domain/feedback/repository/FeedbackRegistrationRepository.java
  src/main/java/org/umc/peerre/domain/feedback/service/FeedbackService.java
  src/main/java/org/umc/peerre/domain/teamspace/repository/TeamspaceRepository.java
  src/main/java/org/umc/peerre/domain/teamspace/repository/UserTeamspaceRepository.java
Labels: FEAT

#16 [feat] 프로젝트 종료 철회 API 구현 & 결과 리포트 조회 API 구현
  src/main/java/org/umc/peerre/domain/feedback/entity/Feedback.java
  src/main/java/org/umc/peerre/domain/feedback/entity/FeedbackAggregation.java
  src/main/java/org/umc/peerre/domain/feedback/service/FeedbackService.java
  src/main/java/org/umc/peerre/domain/project/controller/ProjectController.java
  src/main/java/org/umc/peerre/domain/project/dto/response/MyFeedbackResponseDto.java
  src/main/java/org/umc/peerre/domain/project/dto/response/MyNoFeedbackResponseDto.java
  src/main/java/org/umc/peerre/domain/project/dto/response/MyYesFeedbackResponseDto.java
  src/main/java/org/umc/peerre/domain/project/dto/response/TeamInfoResponseDto.java
  src/main/java/org/umc/peerre/domain/project/repository/ProjectRepository.java
  src/main/java/org/umc/peerre/domain/project/service/ProjectService.java
  src/main/java/org/umc/peerre/global/error/ErrorCode.java
Labels: FEAT

#18 [feat] #5 카카오 로그인
  README.md
  build.gradle
  src/main/java/org/umc/peerre/domain/user/controller/UserController.java
  src/main/java/org/umc/peerre/domain/user/entity/User.java
  src/main/java/org/umc/peerre/domain/user/repository/UserRepository.java
  src/main/java/org/umc/peerre/domain/user/service/UserService.java
  src/main/java/org/umc/peerre/global/config/WebConfig.java
  src/main/java/org/umc/peerre/global/config/auth/ExceptionHandlerFilter.java
  src/main/java/org/umc/peerre/global/config/auth/SecurityConfig.java
  src/main/java/org/umc/peerre/global/config/auth/UserAuthentication.java
  src/main/java/org/umc/peerre/global/config/auth/UserId.java
  src/main/java/org/umc/peerre/global/config/auth/UserIdArgumentResolver.java
  src/main/java/org/umc/peerre/global/config/auth/handelr/CustomAccessDeniedHandler.java
  src/main/java/org/umc/peerre/global/config/auth/handelr/OAuthAuthenticationSuccessHandler.java
  src/main/java/org/umc/peerre/global/config/auth/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/org/umc/peerre/global/config/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/org/umc/peerre/global/config/auth/jwt/JwtProvider.java
  src/main/java/org/umc/peerre/global/config/auth/principal/PrincipalDetails.java
  src/main/java/org/umc/peerre/global/config/auth/principal/PrincipalOAuth2UserService.java
  src/main/java/org/umc/peerre/global/config/auth/principal/userInfo/OAuth2UserInfo.java
  src/main/java/org/umc/peerre/global/config/auth/principal/userInfo/OAuthAttributes.java
  src/main/java/org/umc/peerre/global/error/ErrorCode.java
  src/main/java/org/umc/peerre/global/error/exception/TemporaryException.java
  src/main/java/org/umc/peerre/global/error/handler/GlobalExceptionHandler.java
Labels: FEAT

#20 [feat] #15 팀리포트 조회
  src/main/java/org/umc/peerre/domain/feedback/controller/FeedbackController.java
  src/main/java/org/umc/peerre/domain/feedback/dto/response/FeedbackResponse.java
  src/main/java/org/umc/peerre/domain/feedback/entity/NoFeedbackContent.java
  src/main/java/org/umc/peerre/domain/feedback/entity/YesFeedbackContent.java
  src/main/java/org/umc/peerre/domain/feedback/repository/FeedbackAggregationRepository.java
  src/main/java/org/umc/peerre/domain/feedback/repository/FeedbackRegistrationRepository.java
  src/main/java/org/umc/peerre/domain/feedback/service/FeedbackService.java
  src/main/java/org/umc/peerre/domain/teamspace/repository/UserTeamspaceRepository.java
Labels: FEAT

#21 [feat] #19 회고 등록
  src/main/java/org/umc/peerre/domain/feedback/controller/CommentController.java
  src/main/java/org/umc/peerre/domain/feedback/dto/request/CreateCommentRequestDto.java
  src/main/java/org/umc/peerre/domain/feedback/dto/response/CreateCommentResponseDto.java
  src/main/java/org/umc/peerre/domain/feedback/repository/CommentRepository.java
  src/main/java/org/umc/peerre/domain/feedback/service/CommentService.java
Labels: FEAT

#26 [feat] #22 회고 조회 기능 구현
  src/main/java/org/umc/peerre/domain/project/controller/ProjectController.java
  src/main/java/org/umc/peerre/domain/project/dto/response/comment/CommentListResponseDto.java
  src/main/java/org/umc/peerre/domain/project/dto/response/comment/CreateCommentResponseDto.java
  src/main/java/org/umc/peerre/domain/project/dto/response/comment/EachCommentResponseDto.java
  src/main/java/org/umc/peerre/domain/project/service/CommentService.java
Labels: FEAT

#30 fix/#6 FeedbackAggregation 추가 생성 방지
  src/main/java/org/umc/peerre/domain/feedback/repository/FeedbackAggregationRepository.java
  src/main/java/org/umc/peerre/domain/feedback/service/FeedbackService.java
Labels: FIX

#37 [refactor] #22 API url 수정
  src/main/java/org/umc/peerre/domain/project/controller/ProjectController.java
Labels: REFACTOR

#40 [feat] #39 새 팀 스페이스 생성, 팀 스페이스 조회 구현
  src/main/java/org/umc/peerre/domain/teamspace/constant/Role.java
  src/main/java/org/umc/peerre/domain/teamspace/controller/TeamspaceController.java
  src/main/java/org/umc/peerre/domain/teamspace/dto/request/CreateTeamspaceRequestDto.java
  src/main/java/org/umc/peerre/domain/teamspace/dto/response/CreateTeamspaceResponseDto.java
  src/main/java/org/umc/peerre/domain/teamspace/dto/response/TeamspaceResponseDto.java
  src/main/java/org/umc/peerre/domain/teamspace/dto/response/TeamspacesResponseDto.java
  src/main/java/org/umc/peerre/domain/teamspace/entity/Teamspace.java
  src/main/java/org/umc/peerre/domain/teamspace/entity/UserTeamspace.java
  src/main/java/org/umc/peerre/domain/teamspace/repository/UserTeamspaceRepository.java
  src/main/java/org/umc/peerre/domain/teamspace/service/TeamspaceService.java
Labels: FEAT

#42 [feat] #41 팀스페이스의 프로젝트 조회
  src/main/java/org/umc/peerre/domain/teamspace/controller/TeamspaceController.java
  src/main/java/org/umc/peerre/domain/teamspace/dto/response/ProjectResponseDto.java
  src/main/java/org/umc/peerre/domain/teamspace/dto/response/ProjectsResponseDto.java
  src/main/java/org/umc/peerre/domain/teamspace/service/TeamspaceService.java
Labels: FEAT

#46 [feat] #44 팀스페이스 삭제 구현
  src/main/java/org/umc/peerre/domain/teamspace/controller/TeamspaceController.java
  src/main/java/org/umc/peerre/domain/teamspace/entity/Teamspace.java
  src/main/java/org/umc/peerre/domain/teamspace/repository/UserTeamspaceRepository.java
  src/main/java/org/umc/peerre/domain/teamspace/service/TeamspaceService.java
Labels: FEAT

#48 [refactor] #47 팀스페이스 삭제 관련 에러코드 수정
  src/main/java/org/umc/peerre/domain/teamspace/service/TeamspaceService.java
  src/main/java/org/umc/peerre/global/error/ErrorCode.java
Labels: REFACTOR

#49 [feat] 회고 조회 수정
  build.gradle
  src/main/java/org/umc/peerre/domain/project/controller/ProjectController.java
  src/main/java/org/umc/peerre/domain/project/dto/response/comment/CommentListResponseDto.java
  src/main/java/org/umc/peerre/domain/project/dto/response/comment/EachCommentResponseDto.java
  src/main/java/org/umc/peerre/domain/project/repository/CommentRepository.java
  src/main/java/org/umc/peerre/domain/project/service/CommentService.java
  src/main/java/org/umc/peerre/global/config/auth/ExceptionHandlerFilter.java
  src/main/java/org/umc/peerre/global/error/ErrorCode.java
Labels: FEAT

#50 [feat] #33 반환 순서 뒤집기
  src/main/java/org/umc/peerre/domain/project/dto/response/comment/CommentListResponseDto.java
Labels: FEAT

#52 [fix] #51 FeedbackAggregation no피드백 개수 속성 추가
  src/main/java/org/umc/peerre/domain/feedback/entity/FeedbackAggregation.java
Labels: FIX

#54 [feat] #53 피드백 등록, 수정 시에 팀원의 피드백 yes, no 개수 업데이트
  src/main/java/org/umc/peerre/domain/feedback/service/FeedbackService.java
Labels: FEAT

#56 [feat] #55 팀스페이스 생성 시 초대코드 관련 추가 기능 구현
  src/main/java/org/umc/peerre/domain/teamspace/dto/response/CreateTeamspaceResponseDto.java
  src/main/java/org/umc/peerre/domain/teamspace/entity/Teamspace.java
  src/main/java/org/umc/peerre/domain/teamspace/entity/UserTeamspace.java
  src/main/java/org/umc/peerre/domain/teamspace/repository/TeamspaceRepository.java
  src/main/java/org/umc/peerre/domain/teamspace/service/TeamspaceService.java
  src/main/java/org/umc/peerre/global/error/ErrorCode.java
Labels: FEAT

#59 [feat] #58 로그인 이후 프론트엔드 리다이렉트
  src/main/java/org/umc/peerre/global/config/CorsConfig.java
  src/main/java/org/umc/peerre/global/config/auth/ExceptionHandlerFilter.java
  src/main/java/org/umc/peerre/global/config/auth/SecurityConfig.java
  src/main/java/org/umc/peerre/global/config/auth/handelr/OAuthAuthenticationSuccessHandler.java
  src/main/java/org/umc/peerre/global/config/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/org/umc/peerre/global/error/exception/TemporaryException.java
Labels: FEAT

#61 [feat} #57 팀 스페이스에 팀원 추가 (초대코드 이용)
  src/main/java/org/umc/peerre/domain/teamspace/controller/TeamspaceController.java
  src/main/java/org/umc/peerre/domain/teamspace/entity/Teamspace.java
  src/main/java/org/umc/peerre/domain/teamspace/service/TeamspaceService.java
Labels: FEAT

#63 [fix] #62 팀 스페이스 생성 url 수정
  src/main/java/org/umc/peerre/domain/teamspace/controller/TeamspaceController.java
Labels: FIX

#67 [refactor] #66 팀 스페이스 조회 url 수정
  src/main/java/org/umc/peerre/domain/teamspace/controller/TeamspaceController.java
Labels: REFACTOR

#70 [feat] #68 전체 회고 조회
  src/main/java/org/umc/peerre/domain/project/controller/ProjectController.java
  src/main/java/org/umc/peerre/domain/project/dto/response/comment/CommentListResponseDto.java
  src/main/java/org/umc/peerre/domain/project/dto/response/comment/EachCommentResponseDto.java
  src/main/java/org/umc/peerre/domain/project/repository/CommentRepository.java
  src/main/java/org/umc/peerre/domain/project/service/CommentService.java
Labels: FEAT

#71 [feat] #69 사용자 프로필 조회 기능 구현
  src/main/java/org/umc/peerre/domain/user/controller/UserController.java
  src/main/java/org/umc/peerre/domain/user/dto/response/UserInfoResponseDto.java
  src/main/java/org/umc/peerre/domain/user/service/UserService.java
Labels: FEAT

#73 [refactor] #72 회고 등록 검증
  src/main/java/org/umc/peerre/domain/project/controller/ProjectController.java
  src/main/java/org/umc/peerre/domain/project/dto/request/CreateCommentRequestDto.java
Labels: REFACTOR

#75 [fix] #74 팀 스페이스, 프로젝트 조회시 객체 안에 id 추가
  src/main/java/org/umc/peerre/domain/teamspace/dto/response/ProjectResponseDto.java
  src/main/java/org/umc/peerre/domain/teamspace/dto/response/TeamspaceResponseDto.java
Labels: FIX

#77 [fix] #76 피드백 목록 수정
  src/main/java/org/umc/peerre/domain/feedback/dto/request/FeedbackRequest.java
  src/main/java/org/umc/peerre/domain/feedback/service/FeedbackService.java
Labels: FIX
